### ISSUE TITLE
CraftingODST Calling me a faggot in game

### ISSUE THREAD

**Issue by xXAppleFtwXx** [Spellkaze/Spellkaze-Programs#1]
Hey, I was told to post this here so I am posting, basically in the screenshots provided Crafting mentions that I am "Acigar" but he told me later in the screenshot that he was referring that when you write "faggot" it corrects to acigar. And then he later on goes to say that it's okay for him to say it because he is not breaking any rules. I asked him before all of this happened "Hows the ban?" because he has been banned over 2 times in my knowledge. I personally think this level of toxicity should not be tolerated in this server. I don't have screenshots of earlier when they told me to drink bleach, I said them because there were two of them in that scenario the other being StarGalaxys I don't have screenshots of that moment but I'm sure they are available in the logs when mjr is able to look. 

[Screenshot 1](https://www.dropbox.com/s/y1u5hnfyg80ww7h/Untitled.png?dl=0

[Screenshot 2](https://www.dropbox.com/s/sx6li0pze7lw64h/screen.png?dl=0)

thank you so much if you've read all of this and feel free to ask for logs/their side of the story to see who is right as it is a known fact that with most issues there is someone in the wrong and someone in the right. Both of those people will usually fight to be right, but I'm not concerned about being right as of now. I've admitted that I said something to Crafting, but what I said did not give him the right to call me a faggot, or atleast reference it. 

Virtual regards, xXAppleFtwXx.
Regards, Edward.

**Comment by Spellkaze** [comment]
Your report has been accepted and a a punishment have been delivered to the involved party
